services:
  postgres:
    image: postgres:16
    container_name: metric_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=metric
      - POSTGRES_PASSWORD=metric
      - POSTGRES_DB=metricdb
    volumes:
      - /tmp2/mjlee/metric:/var/lib/postgresql/data
    ports:
      - "22215:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U metric -d metricdb'"]
      interval: 600s
      timeout: 60s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"